import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Expir3</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <h1>🔏 Expir3</h1>
      </header>
      <hr></hr>
      <main className={styles.main}>
        <h2 style={heroHeader}>Create your on Chain will</h2>
        <p style={heroText}>Schedule automatic payouts to accounts of your choice as your will or as a fall back.</p>
        <button style={heroActionButton}><a href="#">Create New/ Sign In</a></button>
      </main>
    </div>
  )
}

const heroHeader = {
  fontSize: "50px",
  maxWidth: "400px",
  alignSelf: "start",
  margin: "0 20px",
}

const heroText = {
  fontSize: "25px",
  maxWidth: "700px",
  alignSelf: "start",
  margin: "10px 20px 0 20px",
  color: "gray"
}

const heroActionButton = {
  fontSize: "25px",
  fontWeight: "500",
  backgroundColor: "black",
  color: "white",
  padding: "10px 20px",
  alignSelf: "start",
  margin: "50px 20px 0 20px",
  borderRadius: "7px",
  border: "none"
}
